name: Container CI

on:
  push:
    # Build for main, tags and PRs
    # Builds from PRs are not pushed to the registry because of rules in the steps
    branches:
      # push these changes to the branch 'docker' for container publishing
      - fastcs-dev
    tags:
      - "*"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      TAG: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # All history

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to GitHub Docker Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          target: runtime
          push: false
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Push developer image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          target: developer
          tags: ${{ env.TAG }}-developer:latest
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Push build image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          target: build
          tags: ${{ env.TAG }}-build:latest
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Push runtime image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          target: runtime
          tags: ${{ env.TAG }}-runtime:latest
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
